// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Wooga.Lambda.Logging")]
[assembly: AssemblyProductAttribute("Wooga.Lambda")]
[assembly: AssemblyDescriptionAttribute("Functional primitives for Unity3D")]
[assembly: AssemblyVersionAttribute("0.6.3")]
[assembly: AssemblyFileVersionAttribute("0.6.3")]
[assembly: InternalsVisibleToAttribute("Wooga.Lambda.Logging.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.6.3";
    }
}
