// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Wooga.Lambda.Network")]
[assembly: AssemblyProductAttribute("Wooga.Lambda")]
[assembly: AssemblyDescriptionAttribute("Functional primitives for Unity3D")]
[assembly: AssemblyVersionAttribute("0.3.5")]
[assembly: AssemblyFileVersionAttribute("0.3.5")]
[assembly: InternalsVisibleToAttribute("Wooga.Lambda.Network.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.3.5";
    }
}
