// <auto-generated/>

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Wooga.Lambda.Network")]
[assembly: AssemblyProduct("Wooga.Lambda")]
[assembly: AssemblyDescription("Functional utilities for C#")]
[assembly: AssemblyVersion("0.2.0")]
[assembly: AssemblyFileVersion("0.2.0")]
[assembly: InternalsVisibleTo("Wooga.Lambda.Network.Tests")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.2.0";
    }
}