// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Wooga.Lambda")]
[assembly: AssemblyProductAttribute("Wooga.Lambda")]
[assembly: AssemblyDescriptionAttribute("Functional utilities for C#")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
[assembly: InternalsVisibleToAttribute("Wooga.Lambda.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
