// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Wooga.Lambda")]
[assembly: AssemblyProductAttribute("Wooga.Lambda")]
[assembly: AssemblyDescriptionAttribute("Functional utilities for C#")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
