// <auto-generated/>

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Wooga.Lambda.Parser")]
[assembly: AssemblyProduct("Wooga.Lambda")]
[assembly: AssemblyDescription("Functional primitives for Unity3D")]
[assembly: AssemblyVersion("0.3.4")]
[assembly: AssemblyFileVersion("0.3.4")]
[assembly: InternalsVisibleTo("Wooga.Lambda.Parser.Tests")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string Version = "0.3.4";
    }
}