// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Wooga.Lambda.Parser")]
[assembly: AssemblyProductAttribute("Wooga.Lambda")]
[assembly: AssemblyDescriptionAttribute("Functional primitives for Unity3D")]
[assembly: AssemblyVersionAttribute("0.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0")]
[assembly: InternalsVisibleToAttribute("Wooga.Lambda.Parser.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0";
    }
}
