#pragma once

// System.Reflection.ParameterModifier
struct ParameterModifier_t1364;
struct ParameterModifier_t1364_marshaled;

void ParameterModifier_t1364_marshal(const ParameterModifier_t1364& unmarshaled, ParameterModifier_t1364_marshaled& marshaled);
void ParameterModifier_t1364_marshal_back(const ParameterModifier_t1364_marshaled& marshaled, ParameterModifier_t1364& unmarshaled);
void ParameterModifier_t1364_marshal_cleanup(ParameterModifier_t1364_marshaled& marshaled);
