// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Wooga.Lambda.Storage")]
[assembly: AssemblyProductAttribute("Wooga.Lambda")]
[assembly: AssemblyDescriptionAttribute("Functional primitives for Unity3D")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: InternalsVisibleToAttribute("Wooga.Lambda.Storage.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
